# Generated by Django 4.2.5 on 2023-09-14 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galerija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=100)),
                ('slika', models.ImageField(upload_to='\\galerija-slik')),
                ('opis', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kontakt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Priporočila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avtor', models.CharField(max_length=100)),
                ('mnenje', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Storitev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=100)),
                ('opis', models.TextField()),
                ('cena', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Termini',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stranka_ime', models.CharField(max_length=100)),
                ('datum_storitve', models.DateTimeField()),
                ('kontakt_email', models.EmailField(max_length=254)),
                ('kontakt_telefon', models.CharField(max_length=15)),
                ('dodatne_informacije', models.TextField(blank=True, null=True)),
                ('storitve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detailing.storitev')),
            ],
        ),
    ]
