# Generated by Django 4.2.5 on 2023-09-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontakt',
            name='google_maps_embed',
            field=models.TextField(default='<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d12345.12345!2d-74.12345!3d40.12345!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMjfCsDAwJzUwLjUiTiA3NMKwMzMnMjMuMyJX!5e0!3m2!1sen!2sus!4v1234567890!5m2!1sen!2sus" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>'),
        ),
        migrations.AddField(
            model_name='kontakt',
            name='ime_podjetja',
            field=models.CharField(default='Gorenc Detailing', max_length=100),
        ),
        migrations.AddField(
            model_name='kontakt',
            name='naslov',
            field=models.CharField(default='Hrastno pri Šentrupertu 9', max_length=200),
        ),
    ]
