# Generated by Django 4.2.5 on 2023-10-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailing', '0002_kontakt_google_maps_embed_kontakt_ime_podjetja_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KontaktStranka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('sporocilo', models.TextField()),
                ('vaš_avto', models.CharField(max_length=100)),
            ],
        ),
    ]
