# Generated by Django 4.2.5 on 2023-10-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailing', '0003_kontaktstranka'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kontaktstranka',
            old_name='vaš_avto',
            new_name='vas_avto',
        ),
        migrations.AddField(
            model_name='kontaktstranka',
            name='telefonska_stevilka',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
