# Generated by Django 4.2.5 on 2023-10-05 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detailing', '0004_rename_vaš_avto_kontaktstranka_vas_avto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='galerija',
            name='slika',
            field=models.ImageField(upload_to='galerija-slik'),
        ),
        migrations.AddField(
            model_name='galerija',
            name='avto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='detailing.avto'),
            preserve_default=False,
        ),
    ]
