# Generated by Django 4.2.5 on 2023-10-05 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detailing', '0005_avto_alter_galerija_slika_galerija_avto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galerija',
            name='naslov',
        ),
        migrations.RemoveField(
            model_name='galerija',
            name='opis',
        ),
    ]
