# Generated by Django 4.2.5 on 2023-10-05 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detailing', '0006_remove_galerija_naslov_remove_galerija_opis'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvtoSlike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slika', models.ImageField(upload_to='galerija_slik')),
            ],
        ),
        migrations.RemoveField(
            model_name='avto',
            name='ime',
        ),
        migrations.AddField(
            model_name='avto',
            name='model',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avto',
            name='znamka',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Galerija',
        ),
        migrations.AddField(
            model_name='avtoslike',
            name='avto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detailing.avto'),
        ),
    ]
