# Generated by Django 4.2.5 on 2023-10-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailing', '0007_avtoslike_remove_avto_ime_avto_model_avto_znamka_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avtoslike',
            name='avto',
        ),
        migrations.AddField(
            model_name='avto',
            name='opis',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avto',
            name='slike',
            field=models.ManyToManyField(blank=True, to='detailing.avtoslike'),
        ),
    ]
