# Generated by Django 4.2.5 on 2023-10-05 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detailing', '0008_remove_avtoslike_avto_avto_opis_avto_slike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avto',
            name='slike',
        ),
        migrations.AddField(
            model_name='avtoslike',
            name='avto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='detailing.avto'),
            preserve_default=False,
        ),
    ]
