# Generated by Django 4.2.5 on 2023-10-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailing', '0010_kontakt_delovni_cas'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontaktstranka',
            name='storitev',
            field=models.ManyToManyField(to='detailing.storitev'),
        ),
    ]
