# Generated by Django 4.2.5 on 2023-10-23 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detailing', '0011_kontaktstranka_storitev'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Termini',
        ),
    ]
