# Generated by Django 4.2.5 on 2023-12-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailing', '0013_storitev_picture_alter_kontakt_google_maps_embed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storitev',
            name='picture',
        ),
        migrations.AddField(
            model_name='storitev',
            name='icon_class',
            field=models.CharField(default=0, help_text='Add the icon class for this service', max_length=50),
            preserve_default=False,
        ),
    ]
