# Generated by Django 4.2.5 on 2023-12-18 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailing', '0014_remove_storitev_picture_storitev_icon_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarLineSlike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_line_slika', models.ImageField(upload_to='')),
            ],
        ),
    ]
