# Generated by Django 4.2.6 on 2024-01-08 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailing', '0015_carlineslike'),
    ]

    operations = [
        migrations.AddField(
            model_name='priporočila',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
