# Generated by Django 4.2.6 on 2024-01-08 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detailing', '0018_priporočila_datum_storitve_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priporočila',
            name='type_of_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='detailing.storitev', verbose_name='Vrsta storitve'),
        ),
    ]
