# Generated by Django 4.2.6 on 2024-01-08 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detailing', '0019_alter_priporočila_type_of_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priporočila',
            name='type_of_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='detailing.storitev', verbose_name='Vrsta storitve'),
        ),
    ]
