# Generated by Django 5.0.1 on 2024-01-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailing', '0020_alter_priporočila_type_of_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storitev',
            name='cena',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
