# Generated by Django 5.0.1 on 2024-01-14 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailing', '0021_alter_storitev_cena'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storitev',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='storitev',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
